# Generated by Django 5.0.14 on 2026-03-28 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='payment_qr_code',
            field=models.ImageField(blank=True, help_text='Upload your UPI or Bank QR code here', null=True, upload_to='campaigns/qr_codes/'),
        ),
        migrations.CreateModel(
            name='CampaignProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='campaigns/proofs/')),
                ('document_type', models.CharField(choices=[('IDENTITY', 'Identity Proof'), ('MEDICAL', 'Medical Document'), ('FINANCIAL', 'Financial Estimate'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='campaigns.campaign')),
            ],
        ),
    ]
