# Generated by Django 5.0.14 on 2026-03-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_payment_qr_code_campaignproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='amount_issued',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid out to the seeker', max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status_reason',
            field=models.TextField(blank=True, help_text='Reason for current status or rejection notes', null=True),
        ),
    ]
